version: '3'
services:

  fossils-db:
    container_name: fossils-db
    image: fossils-db
    build: ./db
    restart: always
    ports:
      - 5442:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  fossils-app:
    container_name: fossils-app
    image: fossils-app
    build: ./app
    ports:
      - 3001:8080
    environment:
      PGHOST: fossils-db
      PGPORT: '5432'
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: postgres

  fossils-frontend:
    container_name: fossils-frontend
    image: fossils-frontend
    build: ./frontend
    ports:
      - 3002:8080

  fossils-nginx:
    container_name: fossils-nginx
    image: fossils-nginx
    build: ./nginx
    depends_on:
      - fossils-app
      - fossils-frontend
    ports:
      - 80:80

volumes:
  pgdata:
