version: '3'
services:

  fossils-app:
    container_name: fossils-app
    image: fossils-app
    build: ./app
    ports:
      - 3001:8080

  fossils-frontend:
    container_name: fossils-frontend
    image: fossils-frontend
    build: ./frontend
    ports:
      - 3002:8080

  fossils-nginx:
    container_name: fossils-nginx
    image: fossils-nginx
    build: ./nginx
    depends_on:
      - fossils-app
      - fossils-frontend
    ports:
      - 3000:80
